swagger: "2.0"
info:
  version: "0.2.0"
  title: XPTO EAD
  description: XPTO EAD - API de ensino a distância.
# basepath
basePath: /v1
# schemes
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /professor:
    x-swagger-router-controller: professor
    get:
      tags:
        - Professor
      description: Retornar os professores registrados
      operationId: professorListar
      responses:
        "200":
          description: Success
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    post:
      tags:
        - Professor
      description: Cadastrar professor
      operationId: professorInserir
      parameters:
        - name: body
          in: body
          description: Parâmetros para cadastrar professor
          required: true
          schema:
            $ref: "#/definitions/ProfessorRequest"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error

  /professor/{professor_id}:
    x-swagger-router-controller: professor
    get:
      tags:
        - Professor
      description: Retornar professor
      operationId: professorExibir
      parameters:
        - name: professor_id
          in: path
          description: Id do professor
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    put:
      tags:
        - Professor
      description: Atualizar professor
      operationId: professorAtualizar
      parameters:
        - name: professor_id
          in: path
          description: Id do professor
          required: true
          type: integer
        - name: body
          in: body
          description: Parâmetros para atualizar professor
          required: true
          schema:
            $ref: "#/definitions/ProfessorRequest"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Professor
      description: Remover professor (soft delete)
      operationId: professorRemover
      parameters:
        - name: professor_id
          in: path
          description: Id do professor
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /curso:
    x-swagger-router-controller: curso
    get:
      tags:
        - Curso
      description: Retornar os cursos registrados
      operationId: cursoListar
      responses:
        "200":
          description: Success
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    post:
      tags:
        - Curso
      description: Cadastrar curso
      operationId: cursoInserir
      parameters:
        - name: body
          in: body
          description: Parâmetros para cadastrar curso
          required: true
          schema:
            $ref: "#/definitions/CursoRequest"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error

  /curso/{curso_id}:
    x-swagger-router-controller: curso
    get:
      tags:
        - Curso
      description: Retornar curso
      operationId: cursoExibir
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    put:
      tags:
        - Curso
      description: Atualizar curso
      operationId: cursoAtualizar
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
        - name: body
          in: body
          description: Parâmetros para atualizar curso
          required: true
          schema:
            $ref: "#/definitions/CursoRequest"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Curso
      description: Remover curso (soft delete)
      operationId: CursoRemover
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  #
  /aluno:
    x-swagger-router-controller: aluno
    get:
      tags:
        - Aluno
      description: Retornar os alunos registrados
      operationId: alunoListar
      responses:
        "200":
          description: Success
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    post:
      tags:
        - Aluno
      description: Cadastrar Aluno
      operationId: alunoInserir
      parameters:
        - name: body
          in: body
          description: Parâmetros para cadastrar aluno
          required: true
          schema:
            $ref: "#/definitions/AlunoRequest"
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error

  /aluno/{aluno_id}:
    x-swagger-router-controller: aluno
    get:
      tags:
        - Aluno
      description: Retornar aluno
      operationId: alunoExibir
      parameters:
        - name: aluno_id
          in: path
          description: Id do aluno
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    put:
      tags:
        - Aluno
      description: Atualizar aluno
      operationId: alunoAtualizar
      parameters:
        - name: aluno_id
          in: path
          description: Id do aluno
          required: true
          type: integer
        - name: body
          in: body
          description: Parâmetros para atualizar aluno
          required: true
          schema:
            $ref: "#/definitions/AlunoRequest"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Aluno
      description: Remover aluno (soft delete)
      operationId: AlunoRemover
      parameters:
        - name: aluno_id
          in: path
          description: Id do aluno
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  
  #
  /curso/{curso_id}/aula:
    x-swagger-router-controller: aula
    get:
      tags:
        - Aula
      description: Listar Aulas
      operationId: aulaListar
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    post:
      tags:
        - Aula
      description: Inserir Aula
      operationId: aulaInserir
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
        - name: body
          in: body
          description: Parâmetros para atualizar curso
          required: true
          schema:
            $ref: "#/definitions/AulaRequest"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  
  /curso/{curso_id}/aula/{aula_id}:
    x-swagger-router-controller: aula
    get:
      tags:
        - Aula
      description: Resgatar Aulas
      operationId: aulaResgatar
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
        - name: aula_id
          in: path
          description: Id da aula
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
    put:
      tags:
        - Aula
      description: Atualizar Aula
      operationId: aulaAtualizar
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
        - name: aula_id
          in: path
          description: Id da aula
          required: true
          type: integer
        - name: body
          in: body
          description: Parâmetros para atualizar aula
          required: true
          schema:
            $ref: "#/definitions/AulaRequest"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Aula
      description: Remover aula (soft delete)
      operationId: aulaRemover
      parameters:
        - name: aula_id
          in: path
          description: Id da aula
          required: true
          type: integer
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  /curso/{curso_id}/matricular/{aluno_id}:
    x-swagger-router-controller: curso_aluno
    post:
      tags:
        - Matricula
      description: Matricular Aluno
      operationId: matricularAluno
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
        - name: aluno_id
          in: path
          description: Id do aluno
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

#
  /curso/{curso_id}/aluno:
    x-swagger-router-controller: curso_aluno
    get:
      tags:
        - Matricula
      description: Listar Alunos Matriculados
      operationId: alunoListar
      parameters:
        - name: curso_id
          in: path
          description: Id do curso
          required: true
          type: integer
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error

  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions
definitions:

  ProfessorRequest:
    type: object
    required:
      - nome
    properties:
      nome:
        type: string

  AulaRequest:
    type: object
    required:
      - titulo
      - conteudo
    properties:
      titulo:
        type: string
      conteudo:
        type: string

  AlunoRequest:
    type: object
    required:
      - nome
      - data_nascimento
    properties:
      nome:
        type: string
      data_nascimento:
        type: string
        format: date

  CursoRequest:
    type: object
    required:
      - professor_id
      - titulo
      - descricao
    properties:
      professor_id:
        type: integer
      titulo:
        type: string
      descricao:
        type: string